### ISSUE TITLE
Ai research guide 

### ISSUE THREAD

**Issue by nikkamit** [Niraj-Lunavat/Artificial-Intelligence#10]
https://github.com/ahmedbahaaeldin/From-0-to-Research-Scientist-resources-guide

**Comment by kuaij** [comment]
您好！

    您正在找回密码，为确保是你本人操作，请在邮箱验证码输入框输入下方验证码：


    
        
            658360
        
    


        如果这不是你本人所为，请忽略。请勿向任何人泄漏您收到的验证码。


    
        
    


        冬奥小助 账号团队敬上
