### ISSUE TITLE
Artificial 

### ISSUE THREAD

**Issue by atik02** [Niraj-Lunavat/Artificial-Intelligence#11]

**Comment by kuaij** [comment]
您好！

    您正在找回密码，为确保是你本人操作，请在邮箱验证码输入框输入下方验证码：


    
        
            658360
        
    


        如果这不是你本人所为，请忽略。请勿向任何人泄漏您收到的验证码。


    
        
    


        冬奥小助 账号团队敬上

**Comment by atik02** [comment]
Hi

Greetings

But i can't understand this language could you please share in English

Regards
Atik

Thanks & Regards
ATik Vora
________________________________
